package com.loe159.rekordbot.mobile.ui.settings

enum class SettingsField {
    TOKEN,
    BASE_ID,
    TABLE,
    TITLE,
    ARTIST,
    SPOTIFY_URL,
    SPOTIFY_TRACK_ID,
    ISRC,
    STATUS,
    REKORDBOT_STATE,
    REKORDBOT_ERROR,
    LAST_SYNC,
    MATCHING_METHOD,
    RAW_GENRE,
    ENERGY,
    MOOD,
    SITUATION,
    INSPIRATIONAL_DJS,
    COMMENT,
    SOURCE,
    DEFAULT_STATUS,
    DEFAULT_SOURCE,
    DEFAULT_REKORDBOT_STATE,
}
